# Generated by Django 2.2.4 on 2019-08-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accesstoken_balcklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessToken',
            new_name='AccessTokenModel',
        ),
        migrations.RenameModel(
            old_name='BalckList',
            new_name='BlackList',
        ),
    ]
